
-- 1. CREAR TABLA PRODUCTS
DROP TABLE IF EXISTS public.products;
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT NOT NULL CHECK (category IN ('coffee', 'derivatives', 'accessories')),
  name JSONB NOT NULL, -- {es: '...', en: '...'}
  badge JSONB,        -- {es: '...', en: '...'}
  score NUMERIC,
  tags JSONB,         -- {es: [...], en: [...]}
  price NUMERIC NOT NULL,
  description JSONB,  -- {es: '...', en: '...'}
  story JSONB,        -- {es: '...', en: '...'}
  image_url TEXT NOT NULL,
  overlay_url TEXT,
  color TEXT,
  mask_type TEXT,
  metadata JSONB,     -- Para configuraciones extra
  stock INTEGER DEFAULT 100,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. POLÍTICAS RLS (Seguridad)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Cualquiera puede ver productos"
  ON public.products FOR SELECT
  USING (true);

CREATE POLICY "Solo admin puede modificar productos"
  ON public.products FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- 3. INSERTAR DATOS INICIALES (MOCK)
INSERT INTO public.products (category, name, badge, score, tags, price, description, story, image_url, overlay_url, color, mask_type)
VALUES 
(
  'coffee',
  '{"es": "Café Malu", "en": "Malu Coffee"}',
  '{"es": "Especialidad Origen Único", "en": "Single Origin Specialty"}',
  88,
  '{"es": ["Frutal", "Chocolate", "Cítrico"], "en": ["Fruity", "Chocolate", "Citrus"]}',
  18.00,
  '{"es": "Cultivado en las elevaciones místicas de la Sierra Nevada, Café Malu ofrece un equilibrio raro de acidez y cuerpo. Experimenta la herencia de generaciones en cada taza.", "en": "Grown in the mystical elevations of Sierra Nevada, Café Malu offers a rare balance of acidity and body. Experience the heritage of generations in every cup."}',
  '{"es": "En lo alto de los picos brumosos de la Sierra Nevada, donde las nubes tocan el suelo, se encuentra el origen de Café Malu. Cultivado por manos que han conocido estas tierras durante siglos, nuestros granos crecen bajo la sombra de árboles nativos, preservando la biodiversidad de la selva.", "en": "High in the misty peaks of the Sierra Nevada, where the clouds touch the soil, lies the origin of Café Malu. Cultivated by hands that have known these lands for centuries, our beans are shade-grown under a canopy of native trees, preserving the biodiversity of the rainforest."}',
  'public/cafe_malu_dual_bags_premium.png',
  NULL,
  '#E0A367',
  'pop'
),
(
  'coffee',
  '{"es": "Sombra Sagrada", "en": "Sacred Shade"}',
  '{"es": "Reserva Ecológica", "en": "Ecological Reserve"}',
  91,
  '{"es": ["Floral", "Jazmín", "Miel"], "en": ["Floral", "Jasmine", "Honey"]}',
  24.00,
  '{"es": "Nuestra reserva más preciada. Un perfil sensorial que evoca los bosques de niebla y la pureza del agua de montaña.", "en": "Our most precious reserve. A sensory profile that evokes the cloud forests and the purity of mountain water."}',
  '{"es": "Sombra Sagrada proviene de microlotes cultivados a más de 1,900m. Cada grano es seleccionado a mano durante el solsticio, respetando los ciclos lunares de la Sierra.", "en": "Sacred Shade comes from microlots grown above 1,900m. Each bean is hand-selected during the solstice, respecting the lunar cycles of the Sierra."}',
  'public/sombra_sagrada_luxury.png',
  'public/sombra_sagrada_sinfondo.png',
  '#1C2923',
  'pop'
),
(
  'accessories',
  '{"es": "Dripper Artesanal", "en": "Artisan Dripper"}',
  '{"es": "Accesorios de Autor", "en": "Designer Accessories"}',
  NULL,
  '{"es": ["Cerámica", "Hecho a mano", "Único"], "en": ["Ceramic", "Handmade", "Unique"]}',
  45.00,
  '{"es": "Piezas únicas moldeadas por el barro de la Sierra, diseñadas para una extracción perfecta y un ritual sagrado.", "en": "Unique pieces molded from Sierra clay, designed for perfect extraction and a sacred ritual."}',
  '{"es": "Creado en colaboración con alfareros locales de la cuenca del Río Gaira, este dripper mantiene la temperatura ideal para resaltar las notas frutales de Origen.", "en": "Created in collaboration with local potters from the Rio Gaira basin, this dripper maintains the ideal temperature to highlight the fruity notes of Origen."}',
  'https://lh3.googleusercontent.com/aida-public/AB6AXuCZv5nOjp7zmCZWGky4raehhN3mKOLVPfk7eSBc9HNBjO5_kEG1uLCwIfoV2zizjbqLyiS1aAl43qdi4ZMZ3OVO59JxWHZp6TgX6Sw11WEvi_-nzkn5hoEVagZgtxAfYnZgN-h8LhD3zDWvYUSqSYDSFQCQSutsQeJpn7hZcVzpF1vXFP9OjLupDWW_HSc7b0YfZAOUNk9jSQA6kohzyMdBLFhCICbYLZlzToOGgmQZufO0hnnEcHt2CHFGM_tqMBUlTY4q109L_afn',
  NULL,
  '#D2B48C',
  NULL
);
